version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - APP_SETTINGS=config.DevelopmentConfig

  redis:
    image: "redis:alpine"

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      #default user : postgres
      #default database : postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
