version: "3.8"

services:
  web:
    expose:
      - 5000
    volumes:
      - .:/code
    environment:
      - APP_SETTINGS=src.config.DevelopmentConfig
    build:
      context: .
      args:
        - MONGO_USERNAME=${MONGO_USERNAME}
        - MONGO_PASSWORD=${MONGO_PASSWORD}
        - MONGO_HOST=mongo
        - MONGO_DATABASE=${MONGO_DATABASE}

  reverse_proxy:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./logrotate-nginx.conf:/etc/logrotate.d/nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - APPLICATION_URL=http://web:5000/

  mongo:
    image: mongo:3.4.4
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - './Data/mongo:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
