version: "3.8"

services:
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - APP_SETTINGS=config.DevelopmentConfig

  db:
    image: postgres:13
    restart: always
    volumes :
      - ./Data/postgre:/data_sql
    environment:
      POSTGRES_PASSWORD: postgres
      #default user : postgres
      #default database : postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - ./Data/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

#  chronograf:
  #  image: chronograf:latest
  #  ports:
  #    - '127.0.0.1:8888:8888'
#    volumes:
#      - .:/var/lib/chronograf
#    depends_on:
#      - influxdb
#    environment:
#      - INFLUXDB_URL=http://influxdb:8086
#      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
  #    - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./Data/grafana:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
