"""empty message

Revision ID: e56d480eec61
Revises: 7174679f9744
Create Date: 2020-12-02 17:30:11.980040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e56d480eec61'
down_revision = '7174679f9744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='articles_pkey')
    )
    # ### end Alembic commands ###
